[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"
[project]
name = "docassemble.base"
version = '1.10.6'
description = "The base components of the docassemble system."
readme = "README.md"
authors = [
  {name = "Jonathan Pyle", email = "jhpyle@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">= 3.12"
dependencies = [
  "aiohappyeyeballs==2.7.1",
  "aiohttp==3.14.3",
  "aiohttp-retry==2.9.1",
  "aiosignal==1.4.0",
  "alembic==1.18.5",
  "astunparse==1.6.3",
  "attrs==26.1.0",
  "azure-common==1.1.28",
  "azure-core==1.41.0",
  "azure-identity==1.25.3",
  "azure-keyvault-secrets==4.11.0",
  "azure-nspkg==3.0.2",
  "azure-storage-blob==12.30.0",
  "babel==2.18.0",
  "backports.tarfile==1.2.0",
  "bcrypt==5.0.0",
  "beautifulsoup4==4.15.0",
  "blinker==1.9.0",
  "boto3==1.43.62",
  "botocore==1.43.62",
  "cachetools==7.1.6",
  "cairocffi==1.7.1",
  "CairoSVG==2.9.0",
  "certifi==2026.7.22",
  "cffi==2.1.0",
  "chardet==7.4.3",
  "charset-normalizer==3.4.9",
  "click==8.4.2",
  "colorama==0.4.6",
  "convertapi==2.0.0",
  "cryptography==49.0.0",
  "cssselect2==0.9.0",
  "defusedxml==0.7.1",
  "Deprecated==1.3.1",
  "deprecation==2.1.0",
  "docassemble-backports==1.0",
  "Docassemble-Pattern==3.6.7",
  "docassemble-mako==0.0.1",
  "docassemble-rtfng==0.0.1",
  "docassemble-textstat==0.7.3",
  "docopt==0.6.2",
  "docutils==0.23",
  "docxcompose==2.2.0",
  "docxtpl==0.20.2",
  "et_xmlfile==2.0.0",
  "exceptiongroup==1.3.1",
  "Flask==3.1.3",
  "Flask-Mail==0.10.0",
  "frozenlist==1.8.0",
  "future==1.0.0",
  "geographiclib==2.1",
  "geopy==2.5.0",
  "google-api-core==2.33.0",
  "google-api-python-client==2.198.0",
  "google-auth==2.56.2",
  "google-auth-httplib2==0.4.0",
  "google-auth-oauthlib==1.4.0",
  "google-cloud-core==2.6.0",
  "google-cloud-storage==3.13.0",
  "google-cloud-vision==3.15.0",
  "google-crc32c==1.8.0",
  "google-i18n-address==3.1.1",
  "google-resumable-media==2.10.0",
  "googleapis-common-protos==1.75.0",
  "greenlet==3.5.4",
  "grpcio==1.83.0",
  "grpcio-status==1.83.0",
  "httplib2==0.32.0",
  "Hyphenate==1.1.0",
  "id==1.6.1",
  "idna==3.18",
  "img2pdf==0.6.3",
  "importlib_metadata==9.0.0",
  "importlib_resources==7.1.0",
  "isodate==0.7.2",
  "itsdangerous==2.2.0",
  "jaraco.classes==3.4.0",
  "jaraco.context==6.1.2",
  "jaraco.functools==4.6.0",
  "jdcal==1.4.1",
  "jeepney==0.9.0",
  "jellyfish==1.2.1",
  "Jinja2==3.1.6",
  "jmespath==1.1.0",
  "joblib==1.5.3",
  "keyring==25.7.0",
  "lxml==6.1.1",
  "Mako==1.3.12",
  "Markdown==3.10.3",
  "markdown-it-py==4.2.0",
  "MarkupSafe==3.0.3",
  "mdurl==0.1.2",
  "more-itertools==11.1.0",
  "msal==1.37.0",
  "msal-extensions==1.3.1",
  "msgpack==1.2.1",
  "msrest==0.7.1",
  "multidict==6.7.1",
  "nh3==0.3.6",
  "nltk==3.10.1",
  "num2words==0.5.14",
  "numpy==2.2.6",
  "oauth2client==4.1.3",
  "oauthlib==3.3.1",
  "openpyxl==3.1.5",
  "ordered-set==4.1.0",
  "packaging==26.2",
  "pandas==2.3.3",
  "pdfminer.six==20260107",
  "phonenumbers==9.0.36",
  "pikepdf==10.11.0",
  "pillow==12.3.0",
  "pkginfo==1.12.1.2",
  "pluggy==1.6.0",
  "portalocker==4.0.0",
  "propcache==0.5.2",
  "proto-plus==1.28.2",
  "protobuf==7.35.1",
  "pwdlib==0.3.0",
  "pyasn1==0.6.4",
  "pyasn1_modules==0.4.2",
  "pycountry==26.2.16",
  "pycparser==3.0",
  "pycryptodome==3.23.0",
  "pycryptodomex==3.23.0",
  "Pygments==2.20.0",
  "PyJWT==2.13.0",
  "PyLaTeX==1.4.2",
  "pyparsing==3.3.2",
  "pypng==0.20220715.0",
  "python-dateutil==2.9.0.post0",
  "python-docx==1.2.0",
  "python-editor==1.0.4",
  "pytz==2026.3.post1",
  "pytz-deprecation-shim==0.1.0.post0",
  "PyYAML==6.0.3",
  "pyzbar==0.1.9",
  "qrcode==8.2",
  "readme_renderer==45.0",
  "regex==2026.7.19",
  "reportlab==5.0.0",
  "requests==2.34.2",
  "requests-oauthlib==2.0.0",
  "requests-toolbelt==1.0.0",
  "rfc3986==2.0.0",
  "rich==15.0.0",
  "rsa==4.9.1",
  "ruamel.yaml==0.19.1",
  "ruamel.yaml.bytes==0.1.0",
  "ruamel.yaml.clib==0.2.15",
  "ruamel.yaml.string==0.1.1",
  "s3transfer==0.19.2",
  "scipy==1.15.3",
  "SecretStorage==3.5.0",
  "setuptools==83.0.0",
  "six==1.17.0",
  "soupsieve==2.9.1",
  "SQLAlchemy==2.0.51",
  "tinycss2==1.5.1",
  "titlecase==2.4.1",
  "toml==0.10.2",
  "tomli==2.4.1",
  "tqdm==4.70.0",
  "twilio==9.10.9",
  "twine==7.0.0",
  "typing_extensions==4.16.0",
  "tzdata==2026.3",
  "tzlocal==5.4.4",
  "ua-parser==1.0.2",
  "ua-parser-builtins==202606",
  "uritemplate==4.2.0",
  "urllib3==2.7.0",
  "us==3.2.0",
  "user-agents==2.2.0",
  "wcwidth==0.8.2",
  "webencodings==0.5.1",
  "Werkzeug==3.1.8",
  "wheel==0.47.0",
  "wrapt==2.3.0",
  "xfdfgen==0.4",
  "xlsxwriter==3.2.9",
  "yarl==1.24.5",
  "zipp==4.1.0"
]
[tool.setuptools.packages.find]
where = ["."]
[project.urls]
Homepage = "https://docassemble.org"
Documentation = "https://docassemble.org/docs.html"
Repository = "https://github.com/jhpyle/docassemble.git"
"Bug Tracker" = "https://github.com/jhpyle/docassemble/issues"
Changelog = "https://github.com/jhpyle/docassemble/blob/master/CHANGELOG.md"
[tool.ruff]
src = ["docassemble_base", "docassemble_webapp", "docassemble_demo"]

[tool.ruff.lint]
ignore = ["E722", "E226", "E24", "E501", "C901", "E305", "E306"]

[tool.pylint.main]
init-hook = """
import sys
sys.path.insert(0, '../docassemble_webapp')
sys.path.insert(0, '../docassemble_base')
sys.path.insert(0, '../docassemble_demo')
"""

[tool.pylint.messages_control]
disable = [
    "attribute-defined-outside-init",
    "bare-except",
    "broad-exception-caught",
    "consider-using-f-string",
    "consider-using-with",
    "eval-used",
    "exec-used",
    "import-outside-toplevel",
    "line-too-long",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-member",
    "protected-access",
    "raise-missing-from",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-function-args",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-positional-arguments",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "global-statement",
]

[tool.mypy]
disable_error_code = ["var-annotated"]